# This file is a general .xdc for the Basys3 rev B board
# To use it in a project:
# - uncomment the lines corresponding to used pins
# - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports Clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports Clk]
	#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {SW[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property PACKAGE_PIN V16 [get_ports {SW[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property PACKAGE_PIN W16 [get_ports {SW[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property PACKAGE_PIN W17 [get_ports {SW[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property PACKAGE_PIN W15 [get_ports {SW[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
set_property PACKAGE_PIN V15 [get_ports {SW[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
set_property PACKAGE_PIN W14 [get_ports {SW[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
set_property PACKAGE_PIN W13 [get_ports {SW[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
set_property PACKAGE_PIN V2 [get_ports {SW[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[8]}]
set_property PACKAGE_PIN T3 [get_ports {SW[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[9]}]
set_property PACKAGE_PIN T2 [get_ports {SW[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[10]}]
set_property PACKAGE_PIN R3 [get_ports {SW[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[11]}]
set_property PACKAGE_PIN W2 [get_ports {SW[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[12]}]
set_property PACKAGE_PIN U1 [get_ports {SW[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[13]}]
set_property PACKAGE_PIN T1 [get_ports {SW[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[14]}]
set_property PACKAGE_PIN R2 [get_ports {SW[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW[15]}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {Finish}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Finish}]
#set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
#set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
#set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
#set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
#set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
#set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
#set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
#set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
#set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
#set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
#set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
	
	
#7 catment display
set_property PACKAGE_PIN W7 [get_ports {Seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {Seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {Seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {Seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {Seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {Seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {Seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Seg[6]}]



set_property PACKAGE_PIN U2 [get_ports {An[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[0]}]
set_property PACKAGE_PIN U4 [get_ports {An[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[1]}]
set_property PACKAGE_PIN V4 [get_ports {An[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[2]}]
set_property PACKAGE_PIN W4 [get_ports {An[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[3]}]


#Buttons
#set_property PACKAGE_PIN U18 [get_ports {Rst[0]}]						
#	set_property IOSTANDARD LVCMOS33 [get_ports {Rst[0]}]
#set_property PACKAGE_PIN T18 [get_ports {Start[1]}]						
#	set_property IOSTANDARD LVCMOS33 [get_ports {Start[1]}]
set_property PACKAGE_PIN W19 [get_ports {Start}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Start}]
#set_property PACKAGE_PIN T17 [get_ports btn[3]]						
#	set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property PACKAGE_PIN U17 [get_ports {Rst}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Rst}]
	
set_property PACKAGE_PIN A18 [get_ports RX]						
	set_property IOSTANDARD LVCMOS33 [get_ports RX]
 


